(function(){
  const SUPABASE_URL='https://fnuncwcsliojhgkmmhwo.supabase.co';
  const SUPABASE_KEY='sb_publishable_jvzxrFRakTBDiQvST5e44w_X60WWMPe';
  const MODEL_URL='https://cdn.jsdelivr.net/npm/@vladmandic/face-api/model/';
  let sb=null, video=null, stream=null, modelsReady=false, activeMode='employees';
  const $=(s,r=document)=>r.querySelector(s);
  function ensure(){if(!sb&&window.supabase?.createClient)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return sb}
  async function getContext(){const c=ensure();if(!c)throw new Error('Supabase client unavailable.');const {data:{session}}=await c.auth.getSession();if(!session)throw new Error('Please login first.');const {data:profile,error}=await c.from('profiles').select('id,business_id,full_name,role,active').eq('id',session.user.id).single();if(error)throw error;if(!profile?.active)throw new Error('Inactive account.');return profile}
  async function loadModels(){if(modelsReady)return;if(!window.faceapi)throw new Error('Face recognition library did not load.');setMsg('Loading face recognition models...');await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL),faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL),faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL)]);modelsReady=true;setMsg('Face recognition ready.')}
  function setMsg(m,err=false){const el=$('#sb-att-msg');if(el){el.textContent=m;el.className=err?'sb-att-msg error':'sb-att-msg'}}
  function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(video){video.pause();video.srcObject=null}}
  async function startCamera(){stopCamera();video=$('#sb-att-video');if(!video)return;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play()}
  function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  function ear(points){return(dist(points[1],points[5])+dist(points[2],points[4]))/(2*dist(points[0],points[3]))}
  async function descriptor(){const d=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.5})).withFaceLandmarks().withFaceDescriptor();if(!d)throw new Error('No clear face detected. Face the camera directly.');return Array.from(d.descriptor)}
  async function liveDescriptor(){const deadline=Date.now()+7000;let open=false,closed=false;setMsg('Look at the camera and blink once...');while(Date.now()<deadline){const d=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.5})).withFaceLandmarks().withFaceDescriptor();if(d){const lm=d.landmarks;const e=(ear(lm.getLeftEye())+ear(lm.getRightEye()))/2;if(e>.24)open=true;if(open&&e<.20)closed=true;if(closed&&e>.24)return{descriptor:Array.from(d.descriptor),liveness:.95}}await new Promise(r=>setTimeout(r,120))}throw new Error('Blink was not detected. Keep one face centered and blink once.')}
  function render(){if($('#sb-att-overlay'))return;const o=document.createElement('div');o.id='sb-att-overlay';o.innerHTML=`<div class="sb-att-modal"><div class="sb-att-head"><div><h2>👥 Employees / Attendance</h2><p>Employee/Staff management and face recognition attendance</p></div><button id="sb-att-close">✕</button></div><div class="sb-att-tabs"><button data-mode="employees" class="active">👥 Employee / Staff</button><button data-mode="kiosk">📷 Attendance Kiosk</button><button data-mode="enroll">👤 Face Enrollment</button><button data-mode="logs">📋 Attendance Logs</button></div><div id="sb-att-body"></div><div id="sb-att-msg" class="sb-att-msg"></div></div>`;document.body.appendChild(o);$('#sb-att-close').onclick=close;o.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{o.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));activeMode=b.dataset.mode;renderMode()});renderMode()}
  function close(){stopCamera();$('#sb-att-overlay')?.remove()}
  async function renderMode(){const body=$('#sb-att-body');if(!body)return;stopCamera();try{const p=await getContext();if(activeMode==='employees'){await renderEmployees(body,p);return}if(activeMode==='logs'){await renderLogs(body,p);return}if(activeMode==='enroll'){if(!['owner','admin','manager'].includes(String(p.role||'').toLowerCase())){body.innerHTML='<div class="sb-att-empty">Only Owner, Admin, or Manager can enroll faces.</div>';return}await loadModels();const {data:employees,error}=await sb.rpc('get_attendance_employees',{p_business_id:p.business_id});if(error)throw error;body.innerHTML=`<div class="sb-att-grid"><div><label>Employee</label><select id="sb-att-employee"><option value="">Select employee...</option>${(employees||[]).map(e=>`<option value="${e.id}">${esc(e.full_name)}${e.has_face?' — enrolled':''}</option>`).join('')}</select><button id="sb-att-enroll" class="primary">📸 Capture & Enroll Face</button></div><div class="sb-att-camera"><video id="sb-att-video" autoplay muted playsinline></video><div class="sb-att-guide">Center one face in the frame.</div></div></div>`;await startCamera();$('#sb-att-enroll').onclick=async()=>{try{const eid=$('#sb-att-employee').value;if(!eid)throw new Error('Select an employee.');const d=await descriptor();setMsg('Saving face template...');const r=await sb.rpc('enroll_employee_face',{p_business_id:p.business_id,p_employee_id:eid,p_face_embedding:d,p_model_name:'@vladmandic/face-api face-recognition-net',p_model_version:'1',p_consent_at:new Date().toISOString()});if(r.error)throw r.error;setMsg('Face enrolled successfully. No raw face photo was stored.')}catch(e){setMsg(e.message||String(e),true)}};return}await loadModels();body.innerHTML=`<div class="sb-att-kiosk"><div class="sb-att-camera large"><video id="sb-att-video" autoplay muted playsinline></video><div class="sb-att-guide">Look at the camera and follow the blink prompt.</div></div><div class="sb-att-actions"><button id="sb-att-in" class="time-in">🟢 TIME IN</button><button id="sb-att-out" class="time-out">🔴 TIME OUT</button></div><div class="sb-att-note">Face template matching happens server-side. Raw face images are not stored.</div></div>`;await startCamera();$('#sb-att-in').onclick=()=>record(p,'time_in');$('#sb-att-out').onclick=()=>record(p,'time_out')}catch(e){body.innerHTML=`<div class="sb-att-empty">${esc(e.message||String(e))}</div>`;setMsg(e.message||String(e),true)}}
  async function renderEmployees(body,p){const canManage=['owner','admin','manager'].includes(String(p.role||'').toLowerCase());const r=await sb.rpc('get_attendance_employees',{p_business_id:p.business_id});if(r.error)throw r.error;const rows=r.data||[];body.innerHTML=`<div class="sb-ea-head"><div><h3>Employee / Staff</h3><p>Add staff records here first, then enroll their face.</p></div>${canManage?'<button id="sb-ea-add" class="primary">＋ Add Employee</button>':''}</div><div id="sb-ea-form"></div><div class="sb-att-table"><table><thead><tr><th>Employee No.</th><th>Name</th><th>Position</th><th>Department</th><th>Face</th><th>Status</th></tr></thead><tbody>${rows.length?rows.map(e=>`<tr><td>${esc(e.employee_no||'—')}</td><td><b>${esc(e.full_name)}</b></td><td>${esc(e.position||'—')}</td><td>${esc(e.department||'—')}</td><td>${e.has_face?'✅ Enrolled':'⚪ Not enrolled'}</td><td>${e.active===false?'Inactive':'Active'}</td></tr>`).join(''):'<tr><td colspan="6">No employees yet. Click Add Employee to create the first staff record.</td></tr>'}</tbody></table></div>`;if(canManage)$('#sb-ea-add').onclick=()=>showEmployeeForm(p)}
  function showEmployeeForm(p){const wrap=$('#sb-ea-form');if(!wrap)return;wrap.innerHTML=`<form class="sb-ea-form" id="sb-ea-create"><div class="sb-ea-grid"><div><label>Employee No.</label><input id="sb-ea-no" placeholder="EMP-001"/></div><div><label>Full Name</label><input id="sb-ea-name" required placeholder="Full name"/></div><div><label>Position</label><input id="sb-ea-position" placeholder="Cashier"/></div><div><label>Department</label><input id="sb-ea-department" placeholder="Store Operations"/></div><div><label>Hire Date</label><input id="sb-ea-hire" type="date"/></div></div><div class="sb-ea-actions"><button type="button" id="sb-ea-cancel">Cancel</button><button class="primary">Save Employee</button></div><div id="sb-ea-form-msg"></div></form>`;$('#sb-ea-cancel').onclick=()=>wrap.innerHTML='';$('#sb-ea-create').onsubmit=async e=>{e.preventDefault();const msg=$('#sb-ea-form-msg'),btn=e.currentTarget.querySelector('button.primary');btn.disabled=true;msg.textContent='Saving...';try{const r=await sb.rpc('create_attendance_employee',{p_business_id:p.business_id,p_employee_no:$('#sb-ea-no').value.trim()||null,p_full_name:$('#sb-ea-name').value.trim(),p_position:$('#sb-ea-position').value.trim()||null,p_department:$('#sb-ea-department').value.trim()||null,p_hire_date:$('#sb-ea-hire').value||null});if(r.error)throw r.error;msg.textContent='Employee created successfully.';setTimeout(()=>renderMode(),400)}catch(e){msg.textContent=e.message||String(e);btn.disabled=false}}}
  async function record(p,action){try{const live=await liveDescriptor();setMsg('Matching face...');const r=await sb.rpc('record_face_attendance',{p_business_id:p.business_id,p_face_embedding:live.descriptor,p_action:action,p_liveness_score:live.liveness,p_branch_id:null,p_device_id:localStorage.getItem('smallbiz_attendance_device')||null});if(r.error)throw r.error;const x=r.data||{};setMsg(`${action==='time_in'?'Time In':'Time Out'} recorded for ${x.employee_name||'employee'}.`)}catch(e){setMsg(e.message||String(e),true)}}
  async function renderLogs(body,p){const start=new Date();start.setDate(start.getDate()-7);const r=await sb.rpc('list_attendance',{p_business_id:p.business_id,p_start_date:start.toISOString().slice(0,10),p_end_date:new Date().toISOString().slice(0,10)});if(r.error)throw r.error;const rows=r.data||[];body.innerHTML=`<div class="sb-att-log-head"><b>Last 7 Days</b><button id="sb-att-refresh">🔄 Refresh</button></div><div class="sb-att-table"><table><thead><tr><th>Date</th><th>Employee</th><th>Time In</th><th>Time Out</th><th>Hours</th><th>Method</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${x.attendance_date}</td><td><b>${esc(x.employee_name)}</b></td><td>${fmt(x.time_in)}</td><td>${fmt(x.time_out)}</td><td>${Number(x.regular_hours||0).toFixed(2)}</td><td>${esc(x.recognition_method||'manual')}</td></tr>`).join(''):'<tr><td colspan="6">No attendance records.</td></tr>'}</tbody></table></div>`;$('#sb-att-refresh').onclick=()=>renderLogs(body,p)}
  function fmt(v){return v?new Date(v).toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}):'—'}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
  function addNav(){const nav=document.querySelector('.sidebar-nav');if(!nav)return;let b=nav.querySelector('[data-smallbiz-attendance]');if(b){const label=b.querySelector('b');if(label)label.textContent='Employees / Attendance';return}b=document.createElement('button');b.className='nav-item';b.dataset.smallbizAttendance='1';b.innerHTML='<span>👥</span><b>Employees / Attendance</b>';b.onclick=()=>render();nav.appendChild(b)}
  function boot(){
    const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@vladmandic/face-api/dist/face-api.js';s.onload=()=>setTimeout(addNav,500);s.onerror=()=>console.error('Face recognition library failed to load');document.head.appendChild(s);
    const observer=new MutationObserver(()=>addNav());
    observer.observe(document.body,{childList:true,subtree:true});
    addNav();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();