import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const tabs=[['returns','↩ Returns'],['promos','🏷 Promotions'],['customers','👥 Customers'],['loyalty','⭐ Loyalty'],['branches','🏬 Branches'],['alerts','🔔 Notifications']];
const money=v=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(v||0));
function GrowthCenter({profile,onClose}){
 const [tab,setTab]=useState('returns'),[data,setData]=useState({}),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[loading,setLoading]=useState(false);
 const owner=['owner','admin','manager'].includes(profile?.role);
 async function load(){setLoading(true);setErr('');try{const b=profile.business_id;const qs={
 returns:sb.from('sales_returns').select('id,return_no,reason,refund_method,refund_amount,status,created_at,sale_id').eq('business_id',b).order('created_at',{ascending:false}).limit(200),
 promos:sb.from('promotions').select('id,name,promo_type,value,min_purchase,starts_at,ends_at,active,customer_only').eq('business_id',b).order('created_at',{ascending:false}),
 customers:sb.from('customers').select('id,name,phone,email,address,active,created_at').eq('business_id',b).order('name').limit(500),
 loyalty:sb.from('loyalty_accounts').select('id,customer_id,points_balance,lifetime_points,tier,active,customers(name,phone)').eq('business_id',b).order('points_balance',{ascending:false}).limit(500),
 branches:sb.from('business_branches').select('id,code,name,address,phone,active,is_main,created_at').eq('business_id',b).order('is_main',{ascending:false}).order('name'),
 alerts:sb.from('business_notifications').select('id,title,message,severity,read_at,created_at,notification_type').eq('business_id',b).order('created_at',{ascending:false}).limit(200)};const r=await qs[tab];if(r.error)throw r.error;setData(r.data||[])}catch(e){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[tab,profile?.business_id]);
 async function addBranch(){const name=prompt('Branch name');if(!name)return;const code=prompt('Branch code');if(!code)return;const {error}=await sb.from('business_branches').insert({business_id:profile.business_id,name,code,is_main:(data.length===0)});if(error)setErr(error.message);else{setMsg('Branch created.');load()}}
 async function addPromo(){const name=prompt('Promotion name');if(!name)return;const type=prompt('Type: percent / fixed / buy_x_get_y / price_override','percent');const value=Number(prompt('Value','10'));if(!Number.isFinite(value))return;const {error}=await sb.from('promotions').insert({business_id:profile.business_id,name,promo_type:type,value,created_by:profile.id});if(error)setErr(error.message);else{setMsg('Promotion created.');load()}}
 async function addCustomer(){const name=prompt('Customer name');if(!name)return;const phone=prompt('Phone')||null;const {error}=await sb.from('customers').insert({business_id:profile.business_id,name,phone});if(error)setErr(error.message);else{setMsg('Customer created.');load()}}
 function rows(){if(tab==='returns')return data.map(x=><tr key={x.id}><td>{x.return_no}</td><td>{x.reason}</td><td>{x.refund_method}</td><td>{money(x.refund_amount)}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>);if(tab==='promos')return data.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.promo_type}</td><td>{x.value}</td><td>{x.active?'Active':'Inactive'}</td><td>{x.customer_only?'Customer only':'All customers'}</td></tr>);if(tab==='customers')return data.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.phone||'—'}</td><td>{x.email||'—'}</td><td>{x.active?'Active':'Inactive'}</td></tr>);if(tab==='loyalty')return data.map(x=><tr key={x.id}><td>{x.customers?.name||'—'}</td><td>{x.customers?.phone||'—'}</td><td>{x.points_balance}</td><td>{x.lifetime_points}</td><td>{x.tier}</td></tr>);if(tab==='branches')return data.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.address||'—'}</td><td>{x.is_main?'Main':'Branch'}</td><td>{x.active?'Active':'Inactive'}</td></tr>);return data.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.message}</td><td>{x.severity}</td><td>{x.read_at?'Read':'Unread'}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}
 const headers={returns:['Return #','Reason','Refund','Amount','Status','Date'],promos:['Promotion','Type','Value','Status','Audience'],customers:['Customer','Phone','Email','Status'],loyalty:['Customer','Phone','Points','Lifetime','Tier'],branches:['Code','Name','Address','Type','Status'],alerts:['Title','Message','Severity','Read','Date']}[tab];
 return <div className="gc-overlay"><div className="gc-panel"><header><div><small>SMALLBIZ POS • GROWTH CENTER</small><h2>Business Growth & Operations</h2><p>Unified foundation for returns, promotions, customers, loyalty, branches and notifications.</p></div><button onClick={onClose}>✕</button></header><div className="gc-tabs">{tabs.map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</div>{msg&&<div className="gc-msg">✓ {msg}</div>}{err&&<div className="gc-err">{err}</div>}<div className="gc-toolbar"><button onClick={load}>↻ Refresh</button>{owner&&tab==='branches'&&<button className="primary" onClick={addBranch}>+ Add Branch</button>}{owner&&tab==='promos'&&<button className="primary" onClick={addPromo}>+ Add Promotion</button>}{owner&&tab==='customers'&&<button className="primary" onClick={addCustomer}>+ Add Customer</button>}</div>{loading?<div className="gc-empty">Loading...</div>:<div className="gc-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows()}</tbody></table>{!data.length&&<div className="gc-empty">No records yet.</div>}</div>}<div className="gc-note">Returns, purchasing, customer, promotion and branch foundations are business-scoped. Sensitive management actions are restricted by role/RLS. Mobile polishing remains intentionally deferred.</div></div></div>}
function App(){const [profile,setProfile]=useState(null),[open,setOpen]=useState(false);useEffect(()=>{sb.auth.getSession().then(async({data})=>{if(!data.session)return;const {data:p}=await sb.from('profiles').select('id,business_id,full_name,role,active').eq('id',data.session.user.id).maybeSingle();setProfile(p)})},[]);useEffect(()=>{const openHandler=()=>setOpen(true);window.addEventListener('smallbiz:open-growth-center',openHandler);return()=>window.removeEventListener('smallbiz:open-growth-center',openHandler)},[]);return open&&profile?<GrowthCenter profile={profile} onClose={()=>setOpen(false)}/>:null}
const s=document.createElement('style');s.textContent=`.gc-overlay{position:fixed;inset:0;z-index:120000;background:rgba(15,23,42,.72);padding:20px;overflow:auto}.gc-panel{max-width:1180px;margin:auto;background:#fff;border-radius:20px;padding:22px;box-shadow:0 30px 90px #0005;color:#0f172a}.gc-panel header{display:flex;justify-content:space-between;gap:20px}.gc-panel header small{font-weight:900;letter-spacing:.12em;color:#64748b}.gc-panel header h2{margin:5px 0}.gc-panel header p{margin:0;color:#64748b}.gc-panel header button{height:40px;border:0;border-radius:10px;background:#f1f5f9}.gc-tabs{display:flex;gap:7px;overflow:auto;margin:18px 0}.gc-tabs button,.gc-toolbar button{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:9px 12px;font-weight:800;white-space:nowrap}.gc-tabs .active,.gc-toolbar .primary{background:#1769e0;color:#fff;border-color:#1769e0}.gc-toolbar{display:flex;gap:8px;margin-bottom:12px}.gc-msg,.gc-err,.gc-note{padding:10px;border-radius:10px;margin:10px 0;font-size:13px}.gc-msg{background:#f0fdf4;color:#166534}.gc-err{background:#fef2f2;color:#b91c1c}.gc-note{background:#eff6ff;color:#1e3a8a}.gc-table{overflow:auto;max-height:62vh;border:1px solid #e2e8f0;border-radius:12px}.gc-table table{width:100%;border-collapse:collapse;min-width:700px}.gc-table th,.gc-table td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left;font-size:12px}.gc-table th{position:sticky;top:0;background:#f8fafc}.gc-empty{text-align:center;padding:35px;color:#64748b}@media(max-width:600px){.gc-overlay{padding:7px}.gc-panel{padding:14px;border-radius:15px}}`;document.head.appendChild(s);const r=document.createElement('div');r.id='growth-center-root';document.body.appendChild(r);createRoot(r).render(<App/>);