import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,sb=url&&key?createClient(url,key):null;
const money=v=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(v||0));
const stages=["unfulfilled","processing","packed","shipped","completed"];
const stageLabel=s=>({unfulfilled:"Unfulfilled",processing:"Processing",packed:"Packed",shipped:"Shipped",completed:"Completed"}[s]||String(s||"").replaceAll("_"," "));
function Panel({profile,onClose}){
 const [orders,setOrders]=useState([]),[channels,setChannels]=useState([]),[items,setItems]=useState([]),[reservations,setReservations]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[msg,setMsg]=useState(""),[filter,setFilter]=useState("all"),[search,setSearch]=useState("");
 async function load(){if(!sb||!profile?.business_id)return;setLoading(true);setError("");const {data:chs}=await sb.from("sales_channels").select("id,code,name").eq("business_id",profile.business_id).in("code",["shopee","lazada","tiktok_shop"]);const ids=(chs||[]).map(x=>x.id);if(!ids.length){setChannels([]);setOrders([]);setItems([]);setReservations([]);setLoading(false);return}const [{data:o,error:oe},{data:i,error:ie},{data:r,error:re}]=await Promise.all([sb.from("external_orders").select("*").eq("business_id",profile.business_id).in("sales_channel_id",ids).order("created_at",{ascending:false}).limit(200),sb.from("external_order_items").select("id,external_order_id,product_id,product_channel_mapping_id,external_sku,product_name,quantity,unit_price,line_total").eq("business_id",profile.business_id),sb.from("stock_reservations").select("id,external_order_id,external_order_item_id,product_id,quantity,status").eq("business_id",profile.business_id)]);if(oe||ie||re)setError((oe||ie||re)?.message||"Unable to load fulfillment data");setChannels(chs||[]);setOrders(o||[]);setItems(i||[]);setReservations(r||[]);setLoading(false)}
 useEffect(()=>{load()},[profile?.business_id]);
 const ch=useMemo(()=>Object.fromEntries(channels.map(c=>[c.id,c])),[channels]);
 const rows=useMemo(()=>{const q=search.toLowerCase().trim();return orders.filter(o=>{const status=o.fulfillment_status||"unfulfilled";const ok=filter==="all"||status===filter;const text=`${o.external_order_no} ${ch[o.sales_channel_id]?.name||""}`.toLowerCase();return ok&&(!q||text.includes(q))})},[orders,filter,search,ch]);
 const reservationByOrder=useMemo(()=>{const m={};for(const r of reservations)if(r.status==="reserved")m[r.external_order_id]=(m[r.external_order_id]||0)+Number(r.quantity||0);return m},[reservations]);
 async function advance(o){const current=o.fulfillment_status||"unfulfilled";const idx=stages.indexOf(current);if(idx<0||idx>=stages.length-1)return;const next=stages[idx+1];setBusy(o.id);setError("");setMsg("");try{
   if(next==="processing"||next==="packed"||next==="shipped"){const {error}=await sb.from("external_orders").update({fulfillment_status:next,order_status:next==="shipped"?"shipped":"processing",updated_at:new Date().toISOString()}).eq("id",o.id).eq("business_id",profile.business_id);if(error)throw new Error(error.message)}
   else {const {data,error}=await sb.rpc("fulfill_external_order",{p_external_order_id:o.id});if(error)throw new Error(error.message);if(data===false)throw new Error("Order could not be fulfilled. Check that every item is mapped and reserved.")}
   setMsg(`${o.external_order_no}: ${stageLabel(next)}`);await load();
 }catch(e){setError(e.message||"Unable to update fulfillment")}finally{setBusy("")}}
 async function release(o){setBusy(o.id);setError("");try{const {error}=await sb.rpc("release_external_order_reservation",{p_external_order_id:o.id,p_reason:"Fulfillment cancelled / reservation released"});if(error)throw new Error(error.message);setMsg(`${o.external_order_no}: reservation released`);await load()}catch(e){setError(e.message||"Unable to release reservation")}finally{setBusy("")}}
 return <div className="mff-overlay"><div className="mff-panel"><header className="mff-head"><div><div className="mff-kicker">SMALLBIZ POS</div><h2>🚚 Marketplace Fulfillment</h2><p>Move marketplace orders from reservation through shipment and final fulfillment.</p></div><button className="mff-close" onClick={onClose}>✕</button></header>{msg&&<div className="mff-ok">✓ {msg}</div>}{error&&<div className="mff-error">{error}</div>}<div className="mff-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{stages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select><button onClick={load}>↻ Refresh</button></div>{loading?<div className="mff-empty">Loading...</div>:!rows.length?<div className="mff-empty">No marketplace orders match this view.</div>:<div className="mff-list">{rows.map(o=>{const status=o.fulfillment_status||"unfulfilled",idx=stages.indexOf(status),next=stages[idx+1],its=items.filter(i=>i.external_order_id===o.id),reserved=reservationByOrder[o.id]||0;return <article className="mff-card" key={o.id}><div className="mff-top"><div><b>{ch[o.sales_channel_id]?.name||"Marketplace"}</b><h3>{o.external_order_no}</h3><small>{new Date(o.created_at).toLocaleString("en-PH")} • {o.order_status||"pending"}</small></div><strong>{money(o.total)}</strong></div><div className="mff-progress">{stages.map((s,i)=><div key={s} className={i<=idx?"done":""}><span>{i+1}</span><small>{stageLabel(s)}</small></div>)}</div><div className="mff-meta"><span>Items: {its.length}</span><span>Reserved: {reserved}</span><span>Shipping: {o.shipping_provider||"—"}</span><span>Tracking: {o.tracking_number||"—"}</span></div><div className="mff-actions">{next&&<button disabled={busy===o.id} onClick={()=>advance(o)}>{busy===o.id?"Updating…":`Mark ${stageLabel(next)}`}</button>}{status!=="completed"&&reserved>0&&<button className="secondary" disabled={busy===o.id} onClick={()=>release(o)}>Release Reservation</button>}{status==="completed"&&<span className="complete">✓ Stock deducted & fulfillment posted</span>}</div></article>})}</div>}<div className="mff-note"><b>Accounting flow:</b> reserved stock remains physical stock until final fulfillment. At <b>Completed</b>, the fulfillment function posts the stock deduction and marks the order complete, keeping the marketplace order traceable for sales/COGS reporting.</div></div></div>}
function App(){const [profile,setProfile]=useState(null),[open,setOpen]=useState(()=>{const p=window.__smallbizPendingModuleOpen;const v=Boolean(p?.["smallbiz:open-marketplace-fulfillment"]);if(v)delete p["smallbiz:open-marketplace-fulfillment"];return v});useEffect(()=>{if(!sb)return;const load=async s=>{const uid=s?.user?.id;if(!uid){setProfile(null);return}const {data}=await sb.from("profiles").select("id,business_id,role,active").eq("id",uid).maybeSingle();setProfile(data||null)};sb.auth.getSession().then(({data})=>load(data.session));const {data:{subscription}}=sb.auth.onAuthStateChange((_,s)=>load(s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(window.__SMALLBIZ_REACT_SIDEBAR_OWNER__)return;if(!profile)return;const id="smallbiz-marketplace-fulfillment";const mount=()=>{if(document.getElementById(id))return;const nav=document.querySelector(".sidebar-nav");if(!nav)return;const b=document.createElement("button");b.id=id;b.type="button";b.className="nav-item";b.innerHTML='<span>🚚</span><b>Marketplace Fulfillment</b>';b.onclick=()=>setOpen(true);nav.appendChild(b)};const ob=new MutationObserver(mount);ob.observe(document.body,{childList:true,subtree:true});const t=setTimeout(mount,300);return()=>{ob.disconnect();clearTimeout(t);document.getElementById(id)?.remove()}},[profile?.id]);useEffect(()=>{const handler=()=>setOpen(true);window.addEventListener("smallbiz:open-marketplace-fulfillment",handler);return()=>window.removeEventListener("smallbiz:open-marketplace-fulfillment",handler)},[]);
 return open&&profile?<Panel profile={profile} onClose={()=>setOpen(false)}/>:null}
const style=document.createElement("style");style.textContent=`.mff-overlay{position:fixed;inset:0;z-index:100004;background:rgba(15,23,42,.66);padding:18px;overflow:auto;display:flex;justify-content:center}.mff-panel{width:min(1180px,100%);background:#fff;border-radius:22px;padding:22px;box-shadow:0 30px 90px rgba(0,0,0,.3);color:#0f172a}.mff-head{display:flex;justify-content:space-between;gap:18px}.mff-kicker{font-size:11px;font-weight:800;letter-spacing:.14em;color:#64748b}.mff-head h2{margin:4px 0}.mff-head p{margin:0;color:#64748b}.mff-close{border:0;background:#f1f5f9;border-radius:10px;padding:9px 12px;font-size:18px;height:max-content}.mff-ok,.mff-error,.mff-note{margin:14px 0;padding:11px 13px;border-radius:11px;font-size:13px}.mff-ok{background:#f0fdf4;color:#166534}.mff-error{background:#fef2f2;color:#b91c1c}.mff-note{background:#eff6ff;color:#1e40af;line-height:1.5}.mff-toolbar{display:flex;gap:8px;margin:18px 0}.mff-toolbar input{flex:1;border:1px solid #cbd5e1;border-radius:9px;padding:10px}.mff-toolbar select,.mff-toolbar button{border:1px solid #cbd5e1;border-radius:9px;background:#fff;padding:10px}.mff-list{display:grid;gap:12px}.mff-card{border:1px solid #e2e8f0;border-radius:16px;padding:15px}.mff-top{display:flex;justify-content:space-between;gap:15px}.mff-top h3{margin:4px 0}.mff-top small{color:#64748b}.mff-top>strong{font-size:20px}.mff-progress{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin:16px 0}.mff-progress div{text-align:center;color:#94a3b8}.mff-progress div.done{color:#15803d}.mff-progress span{display:block;width:26px;height:26px;line-height:26px;margin:auto;border-radius:50%;background:#e2e8f0;font-size:12px;font-weight:800}.mff-progress .done span{background:#dcfce7;color:#166534}.mff-progress small{font-size:10px}.mff-meta{display:flex;flex-wrap:wrap;gap:8px}.mff-meta span{background:#f8fafc;padding:7px 9px;border-radius:8px;font-size:11px}.mff-actions{display:flex;gap:8px;align-items:center;margin-top:12px}.mff-actions button{border:0;border-radius:9px;padding:10px 13px;background:#0f172a;color:#fff;font-weight:800}.mff-actions button.secondary{background:#fff;color:#b91c1c;border:1px solid #fecaca}.mff-actions button:disabled{opacity:.45}.complete{color:#15803d;font-weight:800;font-size:12px}.mff-empty{text-align:center;color:#64748b;padding:45px}@media(max-width:700px){.mff-overlay{padding:7px}.mff-panel{padding:15px}.mff-toolbar{flex-wrap:wrap}.mff-toolbar input{flex-basis:100%}.mff-progress small{font-size:8px}.mff-actions{flex-wrap:wrap}}`;document.head.appendChild(style);const root=document.createElement("div");root.id="marketplace-fulfillment-root";document.body.appendChild(root);createRoot(root).render(<App/>);