import { createClient } from "@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL;const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;const sb=url&&key?createClient(url,key):null;
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
async function allowed(){if(!sb)return false;const {data:s}=await sb.auth.getSession();if(!s?.session?.user)return false;const {data,error}=await sb.rpc("is_platform_admin");return !error&&data===true;}
function toast(m,bad=false){const o=document.getElementById("pca-toast");if(o)o.remove();const e=document.createElement("div");e.id="pca-toast";e.textContent=m;e.style.cssText=`position:fixed;right:22px;top:22px;z-index:12000;padding:12px 16px;border-radius:12px;font-weight:700;background:${bad?"#fee2e2":"#dcfce7"};color:${bad?"#991b1b":"#166534"};box-shadow:0 12px 30px rgba(0,0,0,.16)`;document.body.appendChild(e);setTimeout(()=>e.remove(),3500);}
async function channels(id){const {data,error}=await sb.from("sales_channels").select("id,business_id,code,name,enabled,platform_enabled").eq("business_id",id).order("name");if(error)throw error;return data||[];}
export async function openPlatformChannelAdmin(){if(!(await allowed())){toast("Platform Administrator access required.",true);return;}const {data:bs,error}=await sb.from("businesses").select("id,name").order("name");if(error){toast(error.message,true);return;}const root=document.createElement("div");root.id="pca-root";root.innerHTML=`<div style="position:fixed;inset:0;background:rgba(15,23,42,.58);z-index:11000;display:flex;align-items:center;justify-content:center;padding:20px"><div style="width:min(1050px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;padding:24px;box-shadow:0 24px 90px rgba(0,0,0,.3)"><div style="display:flex;justify-content:space-between;align-items:flex-start"><div><h2 style="margin:0 0 5px">🔐 Platform Online Channel Authorization</h2><div style="color:#64748b;font-size:13px">Only the SmallBiz platform administrator can authorize online-platform access for tenants.</div></div><button id="pca-close">✕</button></div><div style="display:grid;grid-template-columns:300px 1fr;gap:18px;margin-top:18px"><div style="border:1px solid #e2e8f0;border-radius:14px;padding:14px"><b>Tenants</b><div id="pca-bs"></div></div><div id="pca-ch" style="border:1px solid #e2e8f0;border-radius:14px;padding:18px">Select a tenant.</div></div></div></div>`;document.body.appendChild(root);document.getElementById("pca-close").onclick=()=>root.remove();const list=document.getElementById("pca-bs");
(bs||[]).forEach((b,i)=>{const x=document.createElement("button");x.textContent=b.name;x.style.cssText="display:block;width:100%;text-align:left;border:1px solid #e2e8f0;background:#fff;border-radius:10px;padding:11px;margin-top:8px;font-weight:700;cursor:pointer";x.onclick=()=>pick(b,x);list.appendChild(x);if(i===0)setTimeout(()=>pick(b,x),0);});
async function pick(b,x){list.querySelectorAll("button").forEach(y=>y.style.background="#fff");x.style.background="#eff6ff";const p=document.getElementById("pca-ch");p.innerHTML="Loading…";try{const cs=await channels(b.id);p.innerHTML=`<h3 style="margin:0 0 5px">${esc(b.name)}</h3><div style="color:#64748b;font-size:13px;margin-bottom:14px">Platform authorization is controlled centrally. Tenant admins cannot override it.</div>`;if(!cs.length){p.innerHTML+="<div style='color:#64748b'>No channels configured.</div>";return;}cs.forEach(c=>{const r=document.createElement("div");r.style.cssText="display:flex;justify-content:space-between;align-items:center;border:1px solid #e2e8f0;border-radius:12px;padding:13px;margin:9px 0";r.innerHTML=`<div><b>${esc(c.name)}</b><div style="font-size:12px;color:#64748b">${esc(c.code)} · Tenant setting: ${c.enabled?"ON":"OFF"}</div></div><button>${c.platform_enabled?"PLATFORM ON":"PLATFORM OFF"}</button>`;const btn=r.querySelector("button");btn.style.cssText="border:0;border-radius:999px;padding:8px 14px;font-weight:800;cursor:pointer";btn.style.background=c.platform_enabled?"#dcfce7":"#fee2e2";btn.style.color=c.platform_enabled?"#166534":"#991b1b";btn.onclick=async()=>{btn.disabled=true;const next=!c.platform_enabled;try{const {error}=await sb.rpc("set_platform_channel_enabled",{p_business_id:b.id,p_channel_id:c.id,p_enabled:next});if(error)throw error;c.platform_enabled=next;btn.textContent=next?"PLATFORM ON":"PLATFORM OFF";btn.style.background=next?"#dcfce7":"#fee2e2";btn.style.color=next?"#166534":"#991b1b";toast(`${c.name}: ${next?"enabled":"disabled"}`);}catch(e){toast(e.message||"Unable to change access",true);}finally{btn.disabled=false;}};p.appendChild(r);});}catch(e){p.innerHTML=`<div style="color:#b91c1c">${esc(e.message||"Unable to load channels")}</div>`;}}
}
